name: Code Quality Check for Pull Requests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  quality-check:
    name: Check
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request' || !github.event.pull_request.draft
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.90.0
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check for linter errors / warnings
        run: cargo clippy --all-targets --all-features

      - name: Run tests
        run: cargo test --all-features --all-targets --no-fail-fast
