pub(crate) mod account_sider;
pub(crate) mod basic;
pub(crate) mod content_frame;

mod accepted_nodes_provider;
mod file_creation_button;
mod file_download_button;
mod file_selection_dialog;
mod folder_bottom_bar;
mod folder_creation_button;
mod folder_view;
mod modify_node_menu;
mod node_details;
mod node_list;
mod path_breadcrumb;
mod path_provider;
mod shared_view;
mod trash_empty_button;
mod trash_provider;
mod trash_view;
