# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: CI (PR)
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths-ignore:
            - "docs/**"
            - ".github/**"
            - "README.md"
            - "CONTRIBUTING.md"
            - ".devcontainer/**"
            - "Dockerfile"
env:
    CARGO_TERM_COLOR: always
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check-formatting:
        name: Check code formatting
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || !github.event.pull_request.draft
        permissions:
            contents: read
            pull-requests: read
        steps:
            - name: Checkout code
              uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a  # Jul 20 2026

            - name: Setup Environment
              uses: ./.github/actions/setup-environment
              with:
                  toolchain: nightly-2026-02-20
                  components: rustfmt

            - name: rs-fmt-check
              uses: clechasseur/rs-fmt-check@42267c4aa5897129b9887a252b8d074043b732db  # Aug 15 2026

            - name: leptosfmt-check
              uses: LesnyRumcajs/leptosfmt-action@456cf9f4dbac80b32de678d28962779ecf19989a  # Jun 19 2026

    lint-build:
        name: Lint build
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || !github.event.pull_request.draft
        permissions:
            contents: read
            pull-requests: read
        steps:
            - name: Checkout code
              uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a  # Jul 20 2026

            - name: Collect commit information
              id: vars
              # Replace / with - in branch names, due to Github limitations
              run: |
                  SHA_SHORT=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
                  echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
                  BRANCH="${GITHUB_REF_NAME//\//-}"
                  echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT

            - name: Setup Environment
              uses: ./.github/actions/setup-environment
              with:
                  components: clippy

            - name: Check for linter errors / warnings
              run: cargo clippy --all-targets --all-features --timings

            - name: Upload build times
              uses: ./.github/actions/upload-artifact
              with:
                  name: "Build times of ${{ steps.vars.outputs.branch_name }} at ${{ steps.vars.outputs.sha_short }}"
                  path: target/cargo-timings/

    test-code:
        name: Run tests
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || !github.event.pull_request.draft
        permissions:
            contents: read
            pull-requests: read
        steps:
            - name: Checkout code
              uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a  # Jul 20 2026

            - name: Collect commit information
              id: vars
              run: |
                  SHA_SHORT=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
                  echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
                  BRANCH="${GITHUB_REF_NAME//\//-}"
                  echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT

            - name: Setup Environment
              uses: ./.github/actions/setup-environment
              with:
                  toolchain: nightly-2026-02-20
                  components: llvm-tools-preview
                  tools: cargo-llvm-cov cargo-nextest

            - name: Run tests
              shell: bash
              # llvm-cov automatically runs tests
              run: |
                  cargo llvm-cov nextest --all-features --no-fail-fast --workspace  \
                  --lcov --output-path lcov-native.info

            # Upload lcov informations as artifact, used by later job
            - name: Upload Native Coverage Artifact
              uses: ./.github/actions/upload-artifact
              with:
                  name: lcov-native
                  path: lcov-native.info

    check-client-build:
        name: Check client build
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || !github.event.pull_request.draft
        permissions:
            contents: read
            pull-requests: read
        steps:
            - name: Checkout code
              uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a  # Jul 20 2026

            - name: Collect commit information
              id: vars
              run: |
                  SHA_SHORT=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
                  echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
                  BRANCH="${GITHUB_REF_NAME//\//-}"
                  echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT

            - name: Detect changes
              uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d  # Aug 5 2026
              id: filter
              with:
                  filters: |
                      client:
                      - 'client/**'
                      - 'common/**'
                      - 'Cargo.toml'
                      - 'Cargo.lock'
                      - 'Trunk.toml'

            - name: Setup Environment
              if: steps.filter.outputs.client == 'true'
              uses: ./.github/actions/setup-environment
              with:
                  target: wasm32-unknown-unknown
                  tools: trunk

            - name: Build WASM Target
              if: steps.filter.outputs.client == 'true'
              run: cargo build --target wasm32-unknown-unknown --release --timings -p crabdrive-client

            - name: Build with Trunk
              if: steps.filter.outputs.client == 'true'
              run: |
                  cd ./client
                  trunk build --release --verbose

            - name: Upload build times as artifact
              if: steps.filter.outputs.client == 'true'
              uses: ./.github/actions/upload-artifact
              with:
                  name: "WASM Build times of ${{ steps.vars.outputs.branch_name }} at ${{ steps.vars.outputs.sha_short }}"
                  path: target/cargo-timings/

    test-wasm-code:
        name: Run WASM tests
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || !github.event.pull_request.draft
        permissions:
            contents: read
            pull-requests: read
        env:
            CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER: wasm-bindgen-test-runner
            CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUSTFLAGS: >-
                -Cinstrument-coverage
                -Zno-profiler-runtime
                -Clink-args=--no-gc-sections
                --cfg=wasm_bindgen_unstable_test_coverage
                --emit=llvm-ir
            CFLAGS_wasm32_unknown_unknown: "-matomics -mbulk-memory"
        steps:
            - name: Checkout code
              uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a  # Jul 20 2026

            - name: Get wasm-bindgen version from Cargo.toml
              id: bindgen_version
              run: |
                    VERSION=$(cargo tree -p wasm-bindgen --depth 0 | head -n 1 | cut -d' ' -f2 | cut -c 2-)
                    echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Setup Environment
              uses: ./.github/actions/setup-environment
              with:
                  toolchain: nightly-2026-02-20
                  components: llvm-tools-preview
                  target: wasm32-unknown-unknown
                  tools: cargo-llvm-cov wasm-bindgen-cli@${{ steps.bindgen_version.outputs.version }}

            - name: Build project
              run: |
                  cargo test --target wasm32-unknown-unknown -p crabdrive-client --no-run

            - name: Test on Chrome
              env:
                  CHROMEDRIVER: chromedriver
              run: |
                  unset RUSTFLAGS
                  source <(cargo llvm-cov show-env --sh)
                  cargo test --target wasm32-unknown-unknown -p crabdrive-client

            - name: Test on Firefox
              env:
                  GECKODRIVER: geckodriver
              run: |
                  unset RUSTFLAGS
                  source <(cargo llvm-cov show-env --sh)
                  cargo test --target wasm32-unknown-unknown -p crabdrive-client

            - name: Generate code coverage
              run: |
                  unset RUSTFLAGS
                  source <(cargo llvm-cov show-env --sh)
                  find . -type f -name "*.profraw"
                  cargo llvm-cov report --target wasm32-unknown-unknown --lcov  --output-path lcov-wasm.info

            - name: Upload WASM Coverage Artifact
              uses: ./.github/actions/upload-artifact
              with:
                  name: lcov-wasm
                  path: lcov-wasm.info

    check-code-cov:
        name: Summarize code coverage
        needs:
            - test-code
            - test-wasm-code
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || !github.event.pull_request.draft
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a  # Jul 20 2026

            # https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
            - name: Collect commit information
              id: vars
              run: |
                  SHA_SHORT=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
                  echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
                  BRANCH="${GITHUB_REF_NAME//\//-}"
                  echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT

            - name: Setup Environment
              uses: ./.github/actions/setup-environment
              with:
                  components: llvm-tools-preview
                  tools: cargo-llvm-cov grcov

            - name: Install lcov
              run: sudo apt-get install --no-install-recommends -y lcov

            - name: Download Native Coverage
              uses: ./.github/actions/download-artifact
              with:
                  name: lcov-native

            - name: Download WASM Coverage
              uses: ./.github/actions/download-artifact
              with:
                  name: lcov-wasm

            # Merge the code coverages of the native and WASM tests
            - name: Merge code coverages
              run: |
                  lcov -a lcov-native.info -a lcov-wasm.info --output-file lcov.info

            - name: Generate HTML report
              run: |
                  mkdir -p coverage-html
                  grcov lcov.info \
                    --source-dir . \
                     \
                    --ignore-not-existing \
                    --ignore "/*" \
                    --ignore "../*" \
                    -t html \
                    -o coverage-html

            - name: Upload HTML coverage report
              id: upload-html
              uses: ./.github/actions/upload-artifact
              with:
                  name: "Test Coverage of ${{ steps.vars.outputs.branch_name }} at ${{ steps.vars.outputs.sha_short }}"
                  path: coverage-html/

            - name: Report code coverage to PR
              uses: zgosalvez/github-actions-report-lcov@b481d6d39d8e437a2395fb817a4bf9b9225811ea  # Sep 12 2026
              with:
                  coverage-files: lcov.info
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  update-comment: true
                  artifact-name: "Test Coverage of ${{ steps.vars.outputs.branch_name }} at ${{ steps.vars.outputs.sha_short }} (Alt)"
                  title-prefix: "Crabdrive"
                  additional-message: >
                      [Download Report for commit `${{ steps.vars.outputs.sha_short }}`](${{ steps.upload-html.outputs.artifact-url }}) <br>
